version: '3.8'

services:
  app:
    image: ${APP_IMAGE_NAME:-zholnik12/devops-for-developers-project-74}:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-postgres}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
    command: ${APP_COMMAND:-make start}

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-postgres} -d ${DATABASE_NAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
